
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let RECORDS=[],SOURCES={},PHOTOS={},selectedSystem='ALL',selectedRecord=null;
async function loadJSON(p){const r=await fetch(p);if(!r.ok)throw Error(`${p}: ${r.status}`);return r.json()}
async function boot(){const a=await Promise.all(['plc','pwm','controllers','devices','sources','photos'].map(x=>loadJSON(`data/${x}.json`)));RECORDS=[...a[0],...a[1],...a[2],...a[3]];SOURCES=a[4];PHOTOS=a[5];fillFilters();renderTabs();render()}
const sk=id=>'mg-atlas-status:'+id,nk=id=>'mg-atlas-note:'+id,gs=id=>localStorage.getItem(sk(id))||'unchecked';
function blob(r){return[r.module,r.type,r.addr,r.name,JSON.stringify(r.fields||{})].join(' ').toLowerCase()}
function sys(r){const t=blob(r);if(t.includes('main hoist'))return'Main Hoist';if(t.includes('auxiliary hoist')||t.includes('aux hoist'))return'Auxiliary Hoist';if(t.includes('luffing'))return'Luffing';if(t.includes('slewing'))return'Slewing';if(t.includes('can'))return'CAN / PLC';return'Common'}
function fillFilters(){$('#typeFilter').innerHTML='<option value="ALL">Все типы</option>'+[...new Set(RECORDS.map(r=>r.type||'FIELD'))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}
function renderTabs(){const ss=['ALL',...new Set(RECORDS.map(sys))];$('#systemTabs').innerHTML=ss.map(x=>`<button class="${x===selectedSystem?'active':''}" data-system="${esc(x)}">${esc(x)}</button>`).join('')}
function rows(){const q=$('#search').value.toLowerCase(),t=$('#typeFilter').value;return RECORDS.filter(r=>(selectedSystem==='ALL'||sys(r)===selectedSystem)&&(t==='ALL'||r.type===t)&&(!q||blob(r).includes(q)))}
function render(){const a=rows();$('#stats').textContent=`Найдено: ${a.length} из ${RECORDS.length}`;$('#grid').innerHTML=a.map(r=>`<article class="card" data-id="${esc(r.id)}"><div class="cardTop"><span class="addr">${esc(r.addr||'—')}</span><span class="statusDot ${gs(r.id)}"></span></div><div class="name">${esc(r.name)}</div><div class="meta">${esc(r.module)} · ${esc(r.type)} · ${esc(sys(r))}</div></article>`).join('')}
function field(r,n){for(const x of n)for(const[k,v]of Object.entries(r.fields||{}))if(k.toLowerCase()===x.toLowerCase()&&v)return v;return''}
function simg(k,p,l){if(!p)return`<div class="block"><h3>${l}</h3>Страница не привязана.</div>`;const src=SOURCES[`${k}:${p}`];return src?`<div class="block"><h3>${l} · page ${p}</h3><img class="srcimg zoomable" data-title="${esc(l)} · page ${p}" src="${src}" loading="lazy"></div>`:`<div class="block"><h3>${l}</h3>Файл страницы не найден.</div>`}
function overview(r){return`<div class="block"><h3>${esc(r.name)}</h3><div class="kv"><div class="k">Address</div><div>${esc(r.addr)}</div><div class="k">Module</div><div>${esc(r.module)}</div>${Object.entries(r.fields||{}).filter(([k])=>!['Manual excerpt','Drawing PDF page','Manual PDF page'].includes(k)).map(([k,v])=>`<div class="k">${esc(k)}</div><div>${esc(v)}</div>`).join('')}</div></div>`}
function flow(r){const f=r.fields||{};return['Device: '+(f['Номер устройства / гидросхемы']||f['Гидравлический номер']||r.addr),'↓','PLC/PWM: '+(f['PLC / PWM привязка']||f['PLC input']||f['Куда приходит сигнал']||'см. схему'),'↓','Cable: '+(f['Разъём / кабель']||'см. схему'),'↓','Function: '+(f['Функция']||f['Описание работы']||f['Для чего нужен']||r.name)].join('\n')}
function trouble(r){const c=(r.cat||'').toLowerCase(),f=r.fields||{},a=[['1. Подтвердить симптом','Сравнить механизм, HMI/PLC и LED.']];if(c.includes('pressure'))a.push(['2. Давление','Сравнить с манометром.'],['3. Сигнал','Проверить 4–20 mA или 24 V contact.']);else if(c.includes('valve')||c.includes('pwm'))a.push(['2. PLC/CAN','Проверить interlocks, PWR, DIA/BUS и OUT.'],['3. Катушка','Напряжение, ток, сопротивление и разъём.'],['4. Гидравлика','Давление и движение spool.']);else a.push(['2. Питание','Проверить supply, 0 V, CAN/PLC и кабель.']);if(f['Проверка'])a.push(['Проверка',f['Проверка']]);return a.map(([h,t])=>`<div class="step"><b>${esc(h)}</b><div>${esc(t)}</div></div>`).join('')}
function renderStatus(r){const st=gs(r.id);$('#pane-status').innerHTML=`<div class="block"><span class="statusDot ${st}"></span> ${st.toUpperCase()}</div><div class="statusGrid">${['on','off','fault','unchecked'].map(x=>`<button class="${st===x?'active':''}" data-st="${x}">${x.toUpperCase()}</button>`).join('')}</div>`;$('#pane-status').querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>{localStorage.setItem(sk(r.id),b.dataset.st);renderStatus(r);render()})}
function openDetail(id){const r=RECORDS.find(x=>x.id===id);if(!r)return;selectedRecord=r;$('#dTitle').textContent=r.name;$('#dSub').textContent=[r.addr,r.module,r.type,sys(r)].join(' · ');$('#pane-overview').innerHTML=overview(r);const dp=parseInt((r.fields||{})['Drawing PDF page']||0)||null,mp=parseInt((r.fields||{})['Manual PDF page']||0)||null;$('#pane-scheme').innerHTML=simg('draw',dp,'Схема')+`<div class="block"><h3>Цепочка</h3><div class="flow">${esc(flow(r))}</div></div>`;$('#pane-manual').innerHTML=simg('manual',mp,'Мануал')+`<div class="block"><h3>Выдержка</h3>${esc((r.fields||{})['Manual excerpt']||'Нет выдержки')}</div><div class="block"><h3>Работа</h3>${esc(field(r,['Функция по мануалу','Функция','Для чего нужен','Описание работы'])||r.name)}</div>`;$('#pane-trouble').innerHTML=trouble(r);const pk=Object.keys(PHOTOS).filter(k=>blob(r).includes(k.toLowerCase()));$('#pane-photos').innerHTML=pk.length?`<div class="gallery">${pk.map(k=>`<img class="srcimg zoomable" src="${PHOTOS[k]}" data-title="${esc(k)}">`).join('')}</div>`:'<div class="block">Фото не привязаны.</div>';renderStatus(r);$('#pane-notes').innerHTML=`<div class="block"><textarea id="noteBox" rows="10">${esc(localStorage.getItem(nk(r.id))||'')}</textarea><button id="saveNote">Сохранить</button></div>`;$('#saveNote').onclick=()=>localStorage.setItem(nk(r.id),$('#noteBox').value);document.querySelectorAll('.pane').forEach(p=>p.classList.remove('active'));$('#pane-overview').classList.add('active');$('#detailTabs').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===0));$('#detail').showModal()}
$('#grid').onclick=e=>{const c=e.target.closest('[data-id]');if(c)openDetail(c.dataset.id)};$('#systemTabs').onclick=e=>{const b=e.target.closest('[data-system]');if(b){selectedSystem=b.dataset.system;renderTabs();render()}};$('#detailTabs').onclick=e=>{const b=e.target.closest('[data-pane]');if(!b)return;$('#detailTabs').querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.pane').forEach(p=>p.classList.remove('active'));$('#pane-'+b.dataset.pane).classList.add('active')};document.addEventListener('click',e=>{const i=e.target.closest('.zoomable');if(i){$('#zImg').src=i.src;$('#zTitle').textContent=i.dataset.title;$('#zoom').showModal()}});$('#closeDetail').onclick=()=>$('#detail').close();$('#closeZoom').onclick=()=>$('#zoom').close();$('#search').oninput=render;$('#typeFilter').onchange=render;$('#clearBtn').onclick=()=>{Object.keys(localStorage).filter(k=>k.startsWith('mg-atlas-status:')).forEach(k=>localStorage.removeItem(k));render()};$('#exportBtn').onclick=()=>alert('Экспорт заметок будет добавлен следующим обновлением.');
boot().catch(e=>$('#stats').textContent='Ошибка: '+e.message);
